### ISSUE TITLE
Can't resolve 'fs' 

### ISSUE THREAD

**Issue by 121arunkumar** [dewizz/ngx-toolkit#26]
I m getting below error while compiling.

Module not found: Error: Can't resolve 'fs' in node_modules\winston\dist\winston'

**Comment by npetillon** [comment]
Hi,
Do you use winston in browser platform?
You should use it instead in server side rendering or in electron application.
In browser platform you could use the default ConsoleLoggerService provider.

**Comment by ArpithaGMGowda** [comment]
i am referring **Angular LoggerService**   

https://github.com/dewizz/ngx-toolkit/tree/master/projects/logger

**Comment by npetillon** [comment]
Okay i will update the documentation for more precision.
You just have to import the module as `LoggerModule.forRoot(Level.INFO)`
The default implementation is a Console logger service.

**Comment by 121arunkumar** [comment]
@npetillon  if i m using consoleloggerservice its working fine but if i use winston logger service which u have described in the doc,then its giving error below error.

ERROR in ./node_modules/winston/dist/winston/tail-file.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\winston\dist\winston'
ERROR in ./node_modules/winston/dist/winston/transports/file.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\winston\dist\winston\transports'

**Comment by npetillon** [comment]
You could not log in a file if you are in browser platform. If you want to do this, you should use a backend API to send your logs and write them in a file.
The winston logger service is for a server or application usage.

**Comment by 121arunkumar** [comment]
@npetillon  do u mean  that winston is only for nodejs application?

**Comment by npetillon** [comment]
@121arunkumar yes that’s it
