### ISSUE TITLE
Error in  WinstonLoggerService

### ISSUE THREAD

**Issue by ArpithaGMGowda** [dewizz/ngx-toolkit#27]
i am getting error 

ERROR in src/app/WinstonLoggerService.ts:3:8 - error TS1259: Module '"C:/..../.../winstontoolkit/toolkit/node_modules/winston/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import winston from 'winston';
         ~~~~~~~

  node_modules/winston/index.d.ts:178:1
    178 export = winston;
        ~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when
using the 'allowSyntheticDefaultImports' flag.

**Comment by ArpithaGMGowda** [comment]
instead of  **import winston from winston** 

i added **import * as winston from 'winston';** 

its resolved but again i got another error like

ERROR in ./node_modules/winston/dist/winston/tail-file.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\703247433\Desktop\winstontoolkit\toolkit\node_modules\winston\dist\winston'
ERROR in ./node_modules/winston/dist/winston/transports/file.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\703247433\Desktop\winstontoolkit\toolkit\node_modules\winston\dist\winston\transports'

**Comment by npetillon** [comment]
Hi,
Same issue as #26
