### ISSUE TITLE
Expires Issue in Chrome

### ISSUE THREAD

**Issue by ebastuart** [dewizz/ngx-toolkit#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Packages

<pre><code>
[x] @ngx-toolkit/cookie
[ ] @ngx-toolkit/device
[ ] @ngx-toolkit/logger
[ ] @ngx-toolkit/spring
</code></pre>

## Current behavior

I have notice that chrome has an issue when I try so set just a session cookie without an expires date. getExpiresDate returns null, if no value set, this causes that the cookie get an expires date of 9999-12-31T23:59:59.000Z.

## Expected behavior

The cookie in chrome should set to session 

## What is the motivation / use case for changing the behavior?

I could solve this problem by setting expires in CookieOptions  to an empty string. 

## Environment

<pre><code>
Angular version: 8.1.2
Ngx-Toolkit version: 8.0.0

Browser:
- [x] Chrome (desktop) version 80.0.3987.132 
</code></pre>

**Comment by npetillon** [comment]
Hi,

Thank you for your interest and the detailed explanations.

The CookieService has a default cookie options as bellow:
```typescript
export const DEFAULT_COOKIE_OPTIONS: CookieOptions = {
  path: '/',
  expires: Infinity
};
```

3 possible solutions:
- We remove the Infinity value but we make a breaking change
- You can already replace the default value: 
```typescript
CookieModule.forRoot({
  path: '/'
})
```
- On `setItem` method you can explicit set the expires value:
```typescript
setItem(key, data, {expires: null})
```

In any case, I note that we must enrich the documentation

**Comment by npetillon** [comment]
Close for inactivity
